<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

/**
 * Protobuf enum <code>Operation\BroadcastRequest\Options</code>
 */
class BroadcastRequest_Options
{
    /**
     * Generated from protobuf enum <code>ROOMIDLE = 0;</code>
     */
    const ROOMIDLE = 0;
    /**
     * Generated from protobuf enum <code>ROOMPEOPLE = 1;</code>
     */
    const ROOMPEOPLE = 1;
    /**
     * Generated from protobuf enum <code>PLAYING = 2;</code>
     */
    const PLAYING = 2;
}

