<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

/**
 * Protobuf enum <code>Operation\BroadcastRequest\Options</code>
 */
class BroadcastRequest_Options
{
    /**
     * Generated from protobuf enum <code>ROOMIDEL = 0;</code>
     */
    const ROOMIDEL = 0;
    /**
     * Generated from protobuf enum <code>ROOMPEOPLE = 1;</code>
     */
    const ROOMPEOPLE = 1;
}

