<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>operation.BroadcastRequest</code>
 */
class BroadcastRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string productKey = 1;</code>
     */
    private $productKey = '';
    /**
     * Generated from protobuf field <code>string topic = 2;</code>
     */
    private $topic = '';
    /**
     * Generated from protobuf field <code>.operation.BroadcastRequest.Options option = 3;</code>
     */
    private $option = 0;
    /**
     * Generated from protobuf field <code>string data = 4;</code>
     */
    private $data = '';

    public function __construct() {
        \GPBMetadata\Operation::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string productKey = 1;</code>
     * @return string
     */
    public function getProductKey()
    {
        return $this->productKey;
    }

    /**
     * Generated from protobuf field <code>string productKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProductKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->productKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string topic = 2;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.operation.BroadcastRequest.Options option = 3;</code>
     * @return int
     */
    public function getOption()
    {
        return $this->option;
    }

    /**
     * Generated from protobuf field <code>.operation.BroadcastRequest.Options option = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOption($var)
    {
        GPBUtil::checkEnum($var, \Operation\BroadcastRequest_Options::class);
        $this->option = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 4;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

}

