<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>operation.CommonReply</code>
 */
class CommonReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ret = 1;</code>
     */
    private $ret = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string response = 3;</code>
     */
    private $response = '';

    public function __construct() {
        \GPBMetadata\Operation::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 ret = 1;</code>
     * @return int
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     * Generated from protobuf field <code>int32 ret = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRet($var)
    {
        GPBUtil::checkInt32($var);
        $this->ret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string response = 3;</code>
     * @return string
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>string response = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, True);
        $this->response = $var;

        return $this;
    }

}

