<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>operation.LaunchRequest</code>
 */
class LaunchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     */
    private $deviceName = '';
    /**
     * Generated from protobuf field <code>int32 playerId = 2;</code>
     */
    private $playerId = 0;
    /**
     * Generated from protobuf field <code>int32 score = 3;</code>
     */
    private $score = 0;
    /**
     * Generated from protobuf field <code>string force = 4;</code>
     */
    private $force = '';

    public function __construct() {
        \GPBMetadata\Operation::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->deviceName;
    }

    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 playerId = 2;</code>
     * @return int
     */
    public function getPlayerId()
    {
        return $this->playerId;
    }

    /**
     * Generated from protobuf field <code>int32 playerId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPlayerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->playerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 score = 3;</code>
     * @return int
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>int32 score = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string force = 4;</code>
     * @return string
     */
    public function getForce()
    {
        return $this->force;
    }

    /**
     * Generated from protobuf field <code>string force = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setForce($var)
    {
        GPBUtil::checkString($var, True);
        $this->force = $var;

        return $this;
    }

}

