<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

/**
 * Protobuf enum <code>Operation\OperateRequest\Options</code>
 */
class OperateRequest_Options
{
    /**
     * Generated from protobuf enum <code>REBOOT = 0;</code>
     */
    const REBOOT = 0;
    /**
     * Generated from protobuf enum <code>SETTING = 1;</code>
     */
    const SETTING = 1;
    /**
     * Generated from protobuf enum <code>STOP = 2;</code>
     */
    const STOP = 2;
}

