<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

/**
 * Protobuf enum <code>Operation\SearchRequest\Options</code>
 */
class SearchRequest_Options
{
    /**
     * Generated from protobuf enum <code>ACCOUNT = 0;</code>
     */
    const ACCOUNT = 0;
    /**
     * Generated from protobuf enum <code>SETTING = 1;</code>
     */
    const SETTING = 1;
    /**
     * Generated from protobuf enum <code>STATUS = 2;</code>
     */
    const STATUS = 2;
    /**
     * Generated from protobuf enum <code>SHADOW = 3;</code>
     */
    const SHADOW = 3;
    /**
     * Generated from protobuf enum <code>BATCHSTATE = 4;</code>
     */
    const BATCHSTATE = 4;
    /**
     * Generated from protobuf enum <code>INFO = 5;</code>
     */
    const INFO = 5;
}

