<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

/**
 * Protobuf enum <code>Operation\SearchRequest\Type</code>
 */
class SearchRequest_Type
{
    /**
     * Generated from protobuf enum <code>SERVER = 0;</code>
     */
    const SERVER = 0;
    /**
     * Generated from protobuf enum <code>LOCAL = 1;</code>
     */
    const LOCAL = 1;
}

