<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Operation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>operation.SearchRequest</code>
 */
class SearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     */
    private $deviceName = '';
    /**
     * Generated from protobuf field <code>.operation.SearchRequest.Options option = 2;</code>
     */
    private $option = 0;
    /**
     * Generated from protobuf field <code>.operation.SearchRequest.Type type = 3;</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Operation::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->deviceName;
    }

    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.operation.SearchRequest.Options option = 2;</code>
     * @return int
     */
    public function getOption()
    {
        return $this->option;
    }

    /**
     * Generated from protobuf field <code>.operation.SearchRequest.Options option = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOption($var)
    {
        GPBUtil::checkEnum($var, \Operation\SearchRequest_Options::class);
        $this->option = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.operation.SearchRequest.Type type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.operation.SearchRequest.Type type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Operation\SearchRequest_Type::class);
        $this->type = $var;

        return $this;
    }

}

