<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catch.proto

namespace Catch;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>catch.pingRequest</code>
 */
class pingRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Catch::initOnce();
        parent::__construct();
    }

}

