<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catchme.proto

namespace GPBMetadata;

class Catchme
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3020a0d63617463686d652e70726f746f120763617463686d65220d0a" .
            "0b70696e6752657175657374221c0a0970696e675265706c79120f0a076d" .
            "65737361676518012001280922280a0a72656752657175657374120d0a05" .
            "6170706964180120012809120b0a03756964180220012809223a0a087265" .
            "675265706c79120b0a03726574180120012805120f0a076d657373616765" .
            "18022001280912100a08726573706f6e7365180320012809326e0a076361" .
            "7463686d6512320a0470696e6712142e63617463686d652e70696e675265" .
            "71756573741a122e63617463686d652e70696e675265706c792200122f0a" .
            "0372656712132e63617463686d652e726567526571756573741a112e6361" .
            "7463686d652e7265675265706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

