<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catch.proto

namespace GPBMetadata;

class Catch
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95020a0b63617463682e70726f746f12056361746368220d0a0b70696e" .
            "6752657175657374221c0a0970696e675265706c79120f0a076d65737361" .
            "676518012001280922280a0a72656752657175657374120d0a0561707069" .
            "64180120012809120b0a03756964180220012809223a0a08726567526570" .
            "6c79120b0a03726574180120012805120f0a076d65737361676518022001" .
            "280912100a08726573706f6e736518032001280932640a05636174636812" .
            "2e0a0470696e6712122e63617463682e70696e67526571756573741a102e" .
            "63617463682e70696e675265706c792200122b0a0372656712112e636174" .
            "63682e726567526571756573741a0f2e63617463682e7265675265706c79" .
            "2200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

