<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catchme.proto

namespace GPBMetadata;

class Catchme
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca020a0d63617463686d652e70726f746f120763617463686d65220d0a" .
            "0b70696e6752657175657374221c0a0970696e675265706c79120f0a076d" .
            "657373616765180120012809224f0a0a72656752657175657374120e0a06" .
            "6170705f6964180120012809120f0a076170705f75696418022001280912" .
            "0e0a0667656e64657218032001280912100a086e69636b6e616d65180420" .
            "012809223a0a087265675265706c79120b0a03726574180120012805120f" .
            "0a076d65737361676518022001280912100a08726573706f6e7365180320" .
            "012809326e0a0763617463686d6512320a0470696e6712142e6361746368" .
            "6d652e70696e67526571756573741a122e63617463686d652e70696e6752" .
            "65706c792200122f0a0372656712132e63617463686d652e726567526571" .
            "756573741a112e63617463686d652e7265675265706c792200620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

