<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae5010a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c64221b0a0b50696e6752657175657374120c0a046e616d6518012001" .
            "2809221c0a0950696e675265706c79120f0a076d65737361676518012001" .
            "2809324a0a0a68656c6c6f776f726c64123c0a0853617948656c6c6f1217" .
            "2e68656c6c6f776f726c642e50696e67526571756573741a152e68656c6c" .
            "6f776f726c642e50696e675265706c79220042360a1b696f2e677270632e" .
            "6578616d706c65732e68656c6c6f776f726c64420f48656c6c6f576f726c" .
            "6450726f746f5001a20203484c57620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

