<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

namespace GPBMetadata;

class Ping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7d0a0a70696e672e70726f746f120470696e67220d0a0b70696e675265" .
            "7175657374221c0a0970696e675265706c79120f0a076d65737361676518" .
            "012001280932340a0470696e67122c0a0470696e6712112e70696e672e70" .
            "696e67526571756573741a0f2e70696e672e70696e675265706c79220062" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

