<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac6010a0a746573742e70726f746f121443617463684d652e436f72652e" .
            "47726565746572221c0a0c48656c6c6f52657175657374120c0a046e616d" .
            "65180120012809221d0a0a48656c6c6f5265706c79120f0a076d65737361" .
            "6765180120012809325d0a074772656574657212520a0853617948656c6c" .
            "6f12222e43617463684d652e436f72652e477265657465722e48656c6c6f" .
            "526571756573741a202e43617463684d652e436f72652e47726565746572" .
            "2e48656c6c6f5265706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

