<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business.proto

namespace Business;

/**
 * Protobuf enum <code>Business\LoginRequest\Gender</code>
 */
class LoginRequest_Gender
{
    /**
     * Generated from protobuf enum <code>F = 0;</code>
     */
    const F = 0;
    /**
     * Generated from protobuf enum <code>M = 1;</code>
     */
    const M = 1;
}

