<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business.proto

namespace Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>business.PlayRequest</code>
 */
class PlayRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>string openId = 2;</code>
     */
    private $openId = '';
    /**
     * Generated from protobuf field <code>string roomId = 3;</code>
     */
    private $roomId = '';

    public function __construct() {
        \GPBMetadata\Business::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string openId = 2;</code>
     * @return string
     */
    public function getOpenId()
    {
        return $this->openId;
    }

    /**
     * Generated from protobuf field <code>string openId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->openId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string roomId = 3;</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->roomId;
    }

    /**
     * Generated from protobuf field <code>string roomId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->roomId = $var;

        return $this;
    }

}

