<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

namespace Ping;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ping.pingRequest</code>
 */
class pingRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Ping::initOnce();
        parent::__construct();
    }

}

