<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace Player;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>player.pingRequest</code>
 */
class pingRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Player::initOnce();
        parent::__construct();
    }

}

