<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace Player;

/**
 */
class playerClient extends \Grpc\BaseStub implements player
{
  /**
   * @param string $hostname hostname
   * @param array $opts channel options
   * @param \Grpc\Channel $channel (optional) re-use channel object
   */
  public function __construct($hostname, $opts, $channel = null)
  {
    parent::__construct($hostname, $opts, $channel);
  }

  /**
   * @param \Player\RegRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function reg(\Player\RegRequest $argument, $metadata = [], $options = []) : \Player\RegReply
  {
    return $this->_simpleRequest('/player.player/reg', $argument, ['\Player\RegReply', 'decode'], $metadata, $options);
  }

  /**
   * @param \Player\PingRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function ping(\Player\PingRequest $argument, $metadata = [], $options = []) : \Player\PingReply
  {
    return $this->_simpleRequest('/player.player/ping', $argument, ['\Player\PingReply', 'decode'], $metadata, $options);
  }

}

