<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace Player;

/**
 */
interface player
{
  /**
   * @param \Player\RegRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function reg(\Player\RegRequest $argument, $metadata = [], $options = []) : \Player\RegReply;
  /**
   * @param \Player\PingRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function ping(\Player\PingRequest $argument, $metadata = [], $options = []) : \Player\PingReply;
}
