<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace CatchMe\Core\Greeter;

/**
 */
interface Greeter
{
  /**
   * Sends a greeting
   * @param \CatchMe\Core\Greeter\HelloRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function SayHello(\CatchMe\Core\Greeter\HelloRequest $argument, $metadata = [], $options = []) : \CatchMe\Core\Greeter\HelloReply;
}
