<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catchme.proto

namespace Catchme;

/**
 */
class catchmeClient extends \Grpc\BaseStub implements catchme
{
  /**
   * @param string $hostname hostname
   * @param array $opts channel options
   * @param \Grpc\Channel $channel (optional) re-use channel object
   */
  public function __construct($hostname, $opts, $channel = null)
  {
    parent::__construct($hostname, $opts, $channel);
  }

  /**
   * @param \Catchme\LoginRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function Login(\Catchme\LoginRequest $argument, $metadata = [], $options = []) : \Catchme\CommonReply
  {
    return $this->_simpleRequest('/catchme.catchme/Login', $argument, ['\Catchme\CommonReply', 'decode'], $metadata, $options);
  }

  /**
   * @param \Catchme\PlayRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function PlayGame(\Catchme\PlayRequest $argument, $metadata = [], $options = []) : \Catchme\CommonReply
  {
    return $this->_simpleRequest('/catchme.catchme/PlayGame', $argument, ['\Catchme\CommonReply', 'decode'], $metadata, $options);
  }

}

