<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catchme.proto

namespace Catchme;

/**
 */
interface catchme
{
  /**
   * @param \Catchme\LoginRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function Login(\Catchme\LoginRequest $argument, $metadata = [], $options = []) : \Catchme\CommonReply;
  /**
   * @param \Catchme\PlayRequest $argument input argument
   * @param array $metadata metadata
   * @param array $options call options
   */
  public function PlayGame(\Catchme\PlayRequest $argument, $metadata = [], $options = []) : \Catchme\CommonReply;
}
